apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  strategy: {}
  selector:
    matchLabels:
      service: redis
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      serviceAccountName: default
      containers:
      - name: rabbitmq
        imagePullPolicy: IfNotPresent
        image: rabbitmq:3.7-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
status: {}
