apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    service: redis
    stage: prod
spec:
  strategy: {}
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - image: redis:4.0.6
          name: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always
status: {}
