apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: ratings
status:
  loadBalancer: {}