apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    service: web
status:
  loadBalancer: {}